spring:
  application:
    name: oauth
  security:
    oauth2:
      client:
        id: oauth-client
        secret: 123456789
        scopes: openid profile read write
        registration:
          oauth-client:
            provider: oauth-server
            client-id: oauth-client
            client-secret: 123456789
            authorization-grant-type: authorization_code
            redirect-uri: "https://api-acmeairlines.ddns.net/oauth/api/v1/public/authorized"
            client-name: oauth-client
            scope: openid,profile,read,write
        provider:
          oauth-server:
            issuer-uri: https://api-acmeairlines.ddns.net/authorization
      token-uri: https://api-acmeairlines.ddns.net/authorization/oauth2/token

server:
  port: 8081
  servlet:
    context-path: /oauth
logging:
  level:
    org:
      springframework:
        security: TRACE
    